name: CI

on:
  push:
    branches:
      - "**"

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22.x

      - name: Install app dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Format
        run: npm run format-check

  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build
        run: docker build -t matiasg19-website .

      - name: Run
        run: docker run --rm matiasg19-website
